version: '3.8'

services:
  node-app:
    build: .
    ports:
      - "7001:7001"
    volumes:
      - ./:/app

  clang-tidy:
    build: ./clang-tidy
    volumes:
      - ./mount:/src/target
    command:
      - /bin/bash
      - /src/target/run_tidy.sh

  infer:
    build: ./infer
    volumes:
      - ./mount:/target
    command:
      - /bin/bash
      - /target/run_infer.sh

  cppcheck:
    build: ./cppcheck
    volumes:
      - ./mount:/src
    command:
      - /bin/sh
      - /src/run_cppcheck.sh