version: '3.8'

services:
  node-app:
    image: node:20-alpine
    ports:
      - "7001:7001"
    working_dir: /app
    volumes:
      - ./node-app:/app
    command: sh -c "npm install && npm run dev"

  clang-tidy:
    build: ./clang-tidy
    volumes:
      - ./mount:/src/target
    command:
      - /bin/bash
      - /src/target/run_tidy.sh

  infer:
    build: ./infer
    volumes:
      - ./mount:/target
    command:
      - /bin/bash
      - /target/run_infer.sh

  cppcheck:
    build: ./cppcheck
    volumes:
      - ./mount:/src
    command:
      - /bin/sh
      - /src/run_cppcheck.sh